;-----------------------------------------------------
; PROGRAM:		new_stdio
; DESCRIPTION:	Standard input/output functions
; AUTHOR:		Alexander Meinke <ameinke@online.de>
; LICENCE:		Public Domain
; ASSEMBLER:	NASM 2.05.01
; LINKER:		ALINK (DOS)
; VERSION:		0.1
;-----------------------------------------------------


%ifndef NEW_STDIO_MAC
	%define NEW_STDIO_MAC

print:
	mov ah, 0x09
	int 0x21
	ret
%endif
